/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoMyJop;

import java.awt.AWTException;
import java.awt.MouseInfo;
import java.awt.Robot;
import java.awt.im.InputContext;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Locale;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rami
 */
public class NewJFrame extends javax.swing.JFrame {

    int times = 1000;
    Robot s;
    FileWriter wdy;
    String user = System.getProperty("user.name");

    String Clicker = "";
    long timeToSleep = 2L;
    TimeUnit time = TimeUnit.SECONDS;

    final ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();

    /*
            s.mouseMove(x, y);
            s.mousePress(InputEvent.BUTTON1_DOWN_MASK);
            s.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
            s.delay(2000);
    
     */
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Delayy = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NameOf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Keys = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Delayy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delayy.setText("5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Delay Time ");

        jButton1.setText("One click");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Initialize");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        NameOf.setText("Name of project");
        NameOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameOfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("in seconds");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("finish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("mouse move");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Keyboard");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Keys.setText("Type here what you want");
        Keys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeysActionPerformed(evt);
            }
        });

        jButton6.setText("Double click");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Timer))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NameOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(66, 66, 66)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Keys, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delayy, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(NameOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Keys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Delayy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Timer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String fixed = NameOf.getText();
        String ou = "import javax.swing.*;\n"
                + "import java.awt.event.*;\n"
                + "import java.awt.event.KeyEvent;\n"
                + "import java.awt.Robot;\n"
                + "import java.awt.event.InputEvent;\n"
                + "import java.util.logging.Level;\n"
                + "import java.util.logging.Logger;\n"
                + "\n"
                + "public class " + fixed + " implements ActionListener {\n"
                + "\n"
                + "    JFrame f1 = new JFrame(\"Log In\");\n"
                + "\n"
                + "    JButton b1;\n"
                + "\n"
                + "    " + fixed + "() {f1.setLocationRelativeTo(null);\n"
                + "\n"
                + "        b1 = new JButton(\"Press here\");\n"
                + "\n"
                + "        f1.setSize(200, 200);\n"
                + "        f1.setVisible(true);\n"
                + "        f1.setLayout(null);\n"
                + "\n"
                + "        f1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);\n"
                + "\n"
                + "        f1.getContentPane().add(b1);\n"
                + "\n"
                + "        b1.setBounds(0, 120, 100, 30);\n"
                + "\n"
                + "        b1.addActionListener(this);\n"
                + "    }\n"
                + "\n"
                + "    public void actionPerformed(ActionEvent e) {try {\n"
                + "        Robot s = new Robot();";
        jButton6.setEnabled(true);
        jButton4.setEnabled(true);
        jButton1.setEnabled(true);
        jButton5.setEnabled(true);
        try {
            wdy = new FileWriter("\"C:\\Users\\ramya\\OneDrive\\Documents\\ "+ NameOf.getText() + ".java");
            wdy.write(ou);

        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // NameOf.setVisible(false);
        jButton2.setVisible(false);
        jButton1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NameOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameOfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameOfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            time.sleep(timeToSleep);
        } catch (InterruptedException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            int x = MouseInfo.getPointerInfo().getLocation().x;
            int y = MouseInfo.getPointerInfo().getLocation().y;
            String cl = "s.mouseMove(" + x + "," + y + ");s.mousePress(InputEvent.BUTTON1_DOWN_MASK);\n"
                    + "            s.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);";
            int Delays = Integer.parseInt(Delayy.getText()) * 1000;
            
            String c2 = "s.delay(" + Delays + ");";
           wdy.write(c2);
           wdy.write(cl);
            
            /*s.mouseMove(1240, 176);
            s.mousePress(InputEvent.BUTTON1_DOWN_MASK);
            s.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
            s.delay(2000);*/
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {                                         
            Robot s = new Robot();
            String fixed = NameOf.getText();
            
            String Main = "MainClass: "+fixed+" \n" +
                    "\n" +
                    "";
            
            FileWriter wady;
            try {
                wady = new FileWriter("C:\\Users\\" + user + "\\Desktop\\" + "manifest.MF");
                wady.write(Main);
                wady.close();
                
            } catch (IOException ex) {
                
            }
            
            String lu = "} catch (Exception ex) {\n"
                    + "        \n"
                    + "    }\n"
                    + "    }\n"
                    + "\n"
                    + "    \n"
                    + "\n"
                    + "    public static void main(String ag[]) {\n"
                    + "        " + fixed + " p1 = new " + fixed + "();\n"
                    + "    }\n"
                    + "}";
            FileWriter asdy;
           /* try {
                asdy = new FileWriter("C:\\Users\\" + user + "\\Desktop\\" + "Helper.bat");
                asdy.write("");
                asdy.close();
                
            } catch (IOException ex) {
                
            }*/
            
            /*Runtime rt = Runtime.getRuntime();
            
            try
            {
                // We are running "dir" and "ping" command on cmd
                Runtime.getRuntime().exec("cmd /c start cmd.exe");
                
            }
            catch (Exception e)
            {
                System.out.println("HEY Buddy ! U r Doing Something Wrong ");
                e.printStackTrace();
            }*/
      /*      Locale english = new Locale("en", "US", "WIN");
        InputContext it = InputContext.getInstance();
        it.selectInputMethod(english);
        
            it.selectInputMethod(new Locale("nl_BE", "Belgium", "WIN"));
            s.delay(2000);
            s.keyPress(67);
            s.keyRelease(67);
            s.keyPress(68);
            s.keyRelease(68);
            s.keyPress(32);
            s.keyRelease(32);
            s.keyPress(68);
            s.keyRelease(68);
            s.keyPress(69);
            s.keyRelease(69);
            
            s.keyPress(83);
            s.keyRelease(83);
            s.keyPress(75);
            s.keyRelease(75);
            s.keyPress(84);
            s.keyRelease(84);
            s.keyPress(79);
            s.keyRelease(79);
            s.keyPress(80);
            s.keyRelease(80);
            s.keyPress(13);
            s.keyRelease(13);*/
            try {
                
                // finisher
                wdy.write(lu);
                wdy.close();
            } catch (Exception ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (AWTException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            time.sleep(timeToSleep);
        } catch (InterruptedException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        int Delays = Integer.parseInt(Delayy.getText()) * 1000;
        String c2 = "s.delay(" + Delays + ");";
        int x = MouseInfo.getPointerInfo().getLocation().x;
        int y = MouseInfo.getPointerInfo().getLocation().y;
        String c12 = "s.mouseMove(" + x + "," + y + ");";
        try {
            wdy.write(c2);
            wdy.write(c12);

            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String r = Keys.getText();
        try {
            Robot s = new Robot();
            //String r = "ramiadell";
            char tempkey = '"';
            int deelay = Integer.parseInt(Delayy.getText()) * 1000;
             
            String oui2 = "s.delay(" + deelay + ");";
            String oui = "String r = " + tempkey + r + tempkey + "; " + "for (int i = 0; i < r.length(); i++) {\n"
                    + "                char c = r.charAt(i);\n"
                    + "                s.delay(1000);\n"
                    + "                if (Character.isUpperCase(c)) {\n"
                    + "                    s.keyPress(KeyEvent.VK_SHIFT);\n"
                    + "                    s.keyPress(KeyEvent.getExtendedKeyCodeForChar(r.charAt(i)));\n"
                    + "                    s.keyRelease(KeyEvent.VK_SHIFT);\n"
                    + "                } else if (KeyEvent.getExtendedKeyCodeForChar(r.charAt(i)) == KeyEvent.VK_PERIOD) {\n"
                    + "                    s.keyPress(110);\n"
                    + "                    s.keyRelease(110);\n"
                    + "                } else if (KeyEvent.getExtendedKeyCodeForChar(r.charAt(i)) == KeyEvent.VK_SPACE) {\n"
                    + "                    s.keyPress(32);\n"
                    + "                    s.keyRelease(32);\n"
                    + "                } else {\n"
                    + "                    s.keyPress(KeyEvent.getExtendedKeyCodeForChar(r.charAt(i)));\n"
                    + "                }\n"
                    + "\n"
                    + "            }";
            wdy.write(oui2);
            wdy.write(oui);

        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AWTException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*    for (int i = 0; i < r.length(); i++) {
                char c = r.charAt(i);
                s.delay(1000);
                if (Character.isUpperCase(c)) {
                    s.keyPress(KeyEvent.VK_SHIFT);
                    s.keyPress(KeyEvent.getExtendedKeyCodeForChar(r.charAt(i)));
                    s.keyRelease(KeyEvent.VK_SHIFT);
                } else if (KeyEvent.getExtendedKeyCodeForChar(r.charAt(i)) == KeyEvent.VK_PERIOD) {
                    s.keyPress(110);
                    s.keyRelease(110);
                } else if (KeyEvent.getExtendedKeyCodeForChar(r.charAt(i)) == KeyEvent.VK_SPACE) {
                    s.keyPress(32);
                    s.keyRelease(32);
                } else {
                    s.keyPress(KeyEvent.getExtendedKeyCodeForChar(r.charAt(i)));
                }

            }*/

        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void KeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeysActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            time.sleep(timeToSleep);
        } catch (InterruptedException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            int x = MouseInfo.getPointerInfo().getLocation().x;
            int y = MouseInfo.getPointerInfo().getLocation().y;
            String cl = "s.mouseMove(" + x + "," + y + ");\n"
                    + "            s.mousePress(InputEvent.BUTTON1_DOWN_MASK);\n"
                    + "            s.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);\n"
                    + "            s.mousePress(InputEvent.BUTTON1_DOWN_MASK);\n"
                    + "            s.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);";
            int Delays = Integer.parseInt(Delayy.getText()) * 1000;
            String c2 = "s.delay(" + Delays + ");";
            wdy.write(cl);
            wdy.write(c2);
            /*s.mouseMove("+x+","+y+");
            s.mousePress(InputEvent.BUTTON1_DOWN_MASK);
            s.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
            s.mousePress(InputEvent.BUTTON1_DOWN_MASK);
            s.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
            s.delay(2000);*/
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // TODO code application logic here
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Delayy;
    private javax.swing.JTextField Keys;
    private javax.swing.JTextField NameOf;
    private javax.swing.JLabel Timer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
